{{- if and .Values.ingress.enabled (eq .Values.ingress.className "gateway-api") (gt (len .Values.ingress.hosts) 0) }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "tiny-test.fullname" . }}-route
  labels:
    app.kubernetes.io/name: {{ include "tiny-test.name" . }}
spec:
  parentRefs:
    - name: {{ include "tiny-test.fullname" . }}-gateway
  hostnames:
  {{- range .Values.ingress.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - matches:
      {{- range .paths }}
        - path:
            type: {{ .pathType | default "PathPrefix" }}
            value: {{ .path }}
      {{- end }}
      backendRefs:
        - name: {{ include "tiny-test.fullname" $ }}
          namespace: {{ $.Release.Namespace | default "default" }}
          port: {{ $.Values.service.port }}
  {{- end }}
{{- else if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tiny-test.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "tiny-test.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
