apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: tiny-test-route
spec:
  parentRefs:
    - name: tiny-test-gateway
  hostnames:
    - tiny-test.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tiny-test
          port: 80
